### ISSUE TITLE
The OwnCloud node does not report status when uploading

### ISSUE THREAD

**Issue by kdo-sw** [Agile-IoT/node-red-contrib-agile-owncloud#3]
There is no way to know if a file upload was successful or not, which can be the case if there for some reason is no network connection. This prevents cleaning up the local files, because the application never knows when the data has arrived to the cloud.

**Comment by brettdaman** [comment]
This is by design. @rosogon  described the component in https://github.com/Agile-IoT/Architecture/issues/5

> Output
> The node is a regular output node and MUST NOT provide input to other nodes. This way, it behaves as the stock File node.

**Comment by rosogon** [comment]
@kdo-sw , @brettdaman : Please, see https://github.com/Agile-IoT/node-red-contrib-agile-googledrive/issues/4#issuecomment-344529129

**Comment by brettdaman** [comment]
v1.0.1 has an output for owncloud status updates. 
Please verify if this is sufficient for your use case.
